/**
 * Configuration options for the LilyLang compiler
 */
class CompilerConfig {
    /**
     * Whether to optimize the generated bytecode
     */
    var optimize: Boolean = false
    
    /**
     * Whether to generate debug information in the bytecode
     */
    var debug: Boolean = false
    
    /**
     * Whether to print verbose output during compilation
     */
    var verbose: Boolean = false
    
    /**
     * The output file name (without extension)
     */
    var outputFileName: String = "output"
    
    /**
     * Whether to continue compilation after errors
     */
    var continueOnError: Boolean = false
    
    /**
     * Maximum number of errors to report before stopping
     */
    var maxErrors: Int = 10
    
    /**
     * Create a default configuration
     */
    companion object {
        /**
         * Create a default configuration
         */
        fun default(): CompilerConfig {
            return CompilerConfig()
        }
        
        /**
         * Create a configuration for development with debug information
         */
        fun development(): CompilerConfig {
            val config = CompilerConfig()
            config.debug = true
            config.verbose = true
            config.continueOnError = true
            return config
        }
        
        /**
         * Create a configuration for production with optimizations
         */
        fun production(): CompilerConfig {
            val config = CompilerConfig()
            config.optimize = true
            config.debug = false
            config.verbose = false
            config.continueOnError = false
            return config
        }
    }
}